<?php

/**
 * @file
 * Contains hook_help and hook_theme.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fdwc_help($route_name, RouteMatchInterface $route_match) {
  $documentation = '';
  if ($route_name === 'help.page.fdwc') {
    $file_name = drupal_get_path('module', 'fdwc') . '/README.md';
    $file = fopen($file_name, 'r');
    $documentation = nl2br(fread($file, filesize($file_name)));
    fclose($file);
  }
  return '<p>' . $documentation . '</p>';
}

/**
 * Implements hook_theme().
 */
function fdwc_theme() {
  return [
    'fdwc_file_download' => [
      'variables' => ['url' => NULL, 'fileName' => NULL],
      'template' => 'fdwc-file-download',
    ],
    'fdwc_file_download_counter' => [
      'variables' => ['counter' => NULL],
      'template' => 'fdwc-file-download-counter',
    ],
  ];
}
